In [2]:
import numpy as np
import pandas as pd
from scipy import stats

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

 Смещённая ковариация

$$
cov_{biased} = \dfrac{1}{n} \displaystyle\sum_{i = 1}^n \left( x_i - \overline{x} \right) \cdot \left( y_i - \overline{y} \right)
$$

In [3]:
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

n = len(x)

x_mean = sum(x) / n
y_mean = sum(y) / n

s = 0

for i in range(n):
    s += (x[i] - x_mean) * (y[i] - y_mean)

cov_biased = s / n
cov_biased

9157.84

$$cov_{XY} = M[(X - M(X))(Y - M(Y))] = M(XY) - M(X)M(Y)=\overline{X \cdot Y} - \overline{X} \cdot \overline{Y}$$


In [4]:
cov_b = np.mean(x*y)-np.mean(x)*np.mean(y)
cov_b

9157.839999999997

In [5]:
# ковариация через cov из numpy
np.cov(x, y, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Несмещённая ковариация

$$
cov = \dfrac{1}{n-1} \displaystyle\sum_{i = 1}^n \left( x_i - \overline{x} \right) \cdot \left( y_i - \overline{y} \right)
$$

In [6]:
cov = s / (n - 1)
cov

10175.377777777778

In [35]:
# ковариация через cov из numpy
np.cov(x, y, ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

коэффициент корреляции Пирсона:
    $$r_{XY} = \dfrac{\sigma_{XY}}{\sigma_X \cdot \sigma_Y}$$

In [39]:
sigma_x = np.std(x, ddof=0)
sigma_y = np.std(y, ddof=0)

r_xy = cov_b/(sigma_x*sigma_y)
r_xy

0.8874900920739158

In [36]:
#коэффициент корреляции Пирсона с использованием функций из библиотек numpy и pandas
np.corrcoef(x,y)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [7]:
x1 = pd.Series([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y1 = pd.Series([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
pearson_pandas = x1.corr(y1, method="pearson")
pearson_pandas

0.8874900920739163

2. Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [2]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [6]:
n = 10
p = 0.95
alpha = 1 - p

In [7]:
M = np.mean(iq)
std = np.std(iq, ddof=1)
M, std

(118.1, 10.54566788359614)

std не известно, используем t (Стьюдента) распределение, доверительный интервал:

$$
P  = \overline{X} + - t_{\alpha / 2} \cdot \dfrac{\sigma}{\sqrt{n}}    
$$

In [8]:
t = stats.t.ppf(1 - alpha / 2, df=n - 1)
print("Доверительный интервал с вероятностью 95%:")
[M - t * std / np.sqrt(n), M + t * std / np.sqrt(n)]


Доверительный интервал с вероятностью 95%:


[110.55608365158724, 125.64391634841274]

3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95

In [9]:
M = 174.2
n = 27
D = 25
p = 0.95

In [ ]:
std известно (через дисперсию), используем Z распределение, доверительный интервал:

$$
P  = \overline{X} + - z_{\alpha / 2} \cdot \dfrac{\sigma}{\sqrt{n}}    
$$

In [14]:
sigm = D ** 0.5
alpha = 1 - p
z = stats.norm.ppf(1 - alpha/2)
z

1.959963984540054

In [12]:
print("Доверительный интервал с вероятностью 95%:")
[M - z * sigm / np.sqrt(n), M + z * sigm / np.sqrt(n)]

Доверительный интервал с вероятностью 95%:


[172.3140237765397, 176.08597622346028]

In [ ]:
#Выбрать тему для курсового проекта
# С темой пока определяюсь.